[server]
mode       ="dev"
version    ="v0.1"
server_name="apigateway"
prefix="/api/v1/open"

[etcdv3]
etcd_endpoints =["127.0.0.1:2379"]
etcd_group     ="/dev"
server_id      ="1"

[[connection]]
conn_type    ="HTTP"
addr         ="127.0.0.1:8000"

[[connection]]
conn_type ="DEBUG"
addr      ="127.0.0.1:8999"
route     =""

[[watch]]
service_name    ="sns"

