// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

/*
Package payload is a generated protocol buffer package.

It is generated from these files:
	payload.proto

It has these top-level messages:
	MossPacket
	Message
*/
package payload

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MossPacket struct {
	ServiceCode uint32   `protobuf:"varint,1,opt,name=service_code,json=serviceCode" json:"service_code,omitempty"`
	Payload     []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Message     *Message `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	UserId      string   `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ClientIp    string   `protobuf:"bytes,5,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
}

func (m *MossPacket) Reset()                    { *m = MossPacket{} }
func (m *MossPacket) String() string            { return proto.CompactTextString(m) }
func (*MossPacket) ProtoMessage()               {}
func (*MossPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MossPacket) GetServiceCode() uint32 {
	if m != nil {
		return m.ServiceCode
	}
	return 0
}

func (m *MossPacket) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MossPacket) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *MossPacket) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MossPacket) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

type Message struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*MossPacket)(nil), "payload.MossPacket")
	proto.RegisterType((*Message)(nil), "payload.Message")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Invoking service

type InvokingClient interface {
	Invoking(ctx context.Context, in *MossPacket, opts ...grpc.CallOption) (*MossPacket, error)
}

type invokingClient struct {
	cc *grpc.ClientConn
}

func NewInvokingClient(cc *grpc.ClientConn) InvokingClient {
	return &invokingClient{cc}
}

func (c *invokingClient) Invoking(ctx context.Context, in *MossPacket, opts ...grpc.CallOption) (*MossPacket, error) {
	out := new(MossPacket)
	err := grpc.Invoke(ctx, "/payload.Invoking/Invoking", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Invoking service

type InvokingServer interface {
	Invoking(context.Context, *MossPacket) (*MossPacket, error)
}

func RegisterInvokingServer(s *grpc.Server, srv InvokingServer) {
	s.RegisterService(&_Invoking_serviceDesc, srv)
}

func _Invoking_Invoking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MossPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokingServer).Invoking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payload.Invoking/Invoking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokingServer).Invoking(ctx, req.(*MossPacket))
	}
	return interceptor(ctx, in, info, handler)
}

var _Invoking_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payload.Invoking",
	HandlerType: (*InvokingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoking",
			Handler:    _Invoking_Invoking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payload.proto",
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xac, 0xcc,
	0xc9, 0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x56, 0x33,
	0x72, 0x71, 0xf9, 0xe6, 0x17, 0x17, 0x07, 0x24, 0x26, 0x67, 0xa7, 0x96, 0x08, 0x29, 0x72, 0xf1,
	0x14, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0xc6, 0x27, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0xf0, 0x06, 0x71, 0x43, 0xc5, 0x9c, 0xf3, 0x53, 0x52, 0x85, 0x24, 0xb8, 0x60, 0x9a, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x21, 0x2d, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2,
	0xc4, 0xf4, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x01, 0x3d, 0x98, 0xad, 0xbe, 0x10,
	0xf1, 0x20, 0x98, 0x02, 0x21, 0x71, 0x2e, 0xf6, 0xd2, 0xe2, 0xd4, 0xa2, 0xf8, 0xcc, 0x14, 0x09,
	0x16, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x36, 0x10, 0xd7, 0x33, 0x45, 0x48, 0x9a, 0x8b, 0x33, 0x39,
	0x27, 0x33, 0x35, 0xaf, 0x24, 0x3e, 0xb3, 0x40, 0x82, 0x15, 0x2c, 0xc5, 0x01, 0x11, 0xf0, 0x2c,
	0x50, 0xd2, 0xe7, 0x62, 0x87, 0x9a, 0x24, 0x24, 0xc4, 0xc5, 0x82, 0xe4, 0x42, 0x30, 0x5b, 0x48,
	0x80, 0x8b, 0x39, 0xb7, 0x38, 0x1d, 0xec, 0x2c, 0xce, 0x20, 0x10, 0xd3, 0xc8, 0x89, 0x8b, 0xc3,
	0x33, 0xaf, 0x2c, 0x3f, 0x3b, 0x33, 0x2f, 0x5d, 0xc8, 0x0c, 0x89, 0x2d, 0x8c, 0x70, 0x19, 0xdc,
	0xf3, 0x52, 0xd8, 0x04, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x41, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x7f, 0xf1, 0x6d, 0x8c, 0x43, 0x01, 0x00, 0x00,
}
