// Code generated by protoc-gen-validate
// source: payload.proto
// DO NOT EDIT!!!

package payload

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/gogo/protobuf/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = types.DynamicAny{}
)

// Validate checks the field values on MossPacket with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *MossPacket) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetServiceCode() <= 10000 {
		return MossPacketValidationError{
			Field:  "ServiceCode",
			Reason: "value must be greater than 10000",
		}
	}

	if len(m.GetPayload()) < 1 {
		return MossPacketValidationError{
			Field:  "Payload",
			Reason: "value length must be at least 1 bytes",
		}
	}

	if v, ok := interface{}(m.GetMossMessage()).(interface {
		Validate() error
	}); ok {
		if err := v.Validate(); err != nil {
			return MossPacketValidationError{
				Field:  "MossMessage",
				Reason: "embedded message failed validation",
				Cause:  err,
			}
		}
	}

	// no validation rules for MossMetadata

	return nil
}

// MossPacketValidationError is the validation error returned by
// MossPacket.Validate if the designated constraints aren't met.
type MossPacketValidationError struct {
	Field  string
	Reason string
	Cause  error
	Key    bool
}

// Error satisfies the builtin error interface
func (e MossPacketValidationError) Error() string {
	cause := ""
	if e.Cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.Cause)
	}

	key := ""
	if e.Key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMossPacket.%s: %s%s",
		key,
		e.Field,
		e.Reason,
		cause)
}

var _ error = MossPacketValidationError{}

// Validate checks the field values on MossMessage with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MossMessage) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Code

	// no validation rules for Msg

	return nil
}

// MossMessageValidationError is the validation error returned by
// MossMessage.Validate if the designated constraints aren't met.
type MossMessageValidationError struct {
	Field  string
	Reason string
	Cause  error
	Key    bool
}

// Error satisfies the builtin error interface
func (e MossMessageValidationError) Error() string {
	cause := ""
	if e.Cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.Cause)
	}

	key := ""
	if e.Key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMossMessage.%s: %s%s",
		key,
		e.Field,
		e.Reason,
		cause)
}

var _ error = MossMessageValidationError{}
